-- Table: Patient
CREATE TABLE Patient (
  NUM_FIC INT AUTO_INCREMENT PRIMARY KEY,
  CIN INT NOT NULL,
  DAT_FIC DATE NOT NULL,
  NOM VARCHAR(50) NOT NULL,
  PRENOM VARCHAR(50) NOT NULL,
  DAT_NAI DATE NOT NULL,
  PROF VARCHAR(50),
  ADRESSE VARCHAR(100),
  PHONE INT,
  SEX CHAR(1) NOT NULL,
  NUM_CNAM INT,
  NUM_RDV INT,
  FOREIGN KEY (NUM_CNAM) REFERENCES CNAM (NUM_CNAM),
  FOREIGN KEY (NUM_RDV) REFERENCES RDV (NUM_RDV)
);

-- Table: CNAM
CREATE TABLE CNAM (
  NUM_CNAM INT AUTO_INCREMENT PRIMARY KEY,
  DATE_VAL_CNAM DATE NOT NULL,
  TYPE_CNAM VARCHAR(50)
);

-- Table: RDV
CREATE TABLE RDV (
  NUM_RDV INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPTION VARCHAR(100),
  DATE_RDV DATE NOT NULL,
  HEURE_RDV DATE
);

-- Table: ANTECEDENT
CREATE TABLE ANTECEDENT (
  NUM_ANT INT AUTO_INCREMENT PRIMARY KEY,
  CATEGORIE VARCHAR(50),
  DESCRIPTION VARCHAR(100),
  PATIENT_ID INT,
  FOREIGN KEY (PATIENT_ID) REFERENCES Patient (NUM_FIC)
);

-- Table: CONSULTATION
CREATE TABLE CONSULTATION (
  NUM_CONS INT AUTO_INCREMENT PRIMARY KEY,
  DATE_CONS DATE NOT NULL,
  MOTIF VARCHAR(100),
  DIAGNOSTIC VARCHAR(100),
  PATIENT_ID INT,
  FOREIGN KEY (PATIENT_ID) REFERENCES Patient (NUM_FIC)
);

-- Table: EXAMEN
CREATE TABLE EXAMEN (
  NUM_EXM INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPTION VARCHAR(100),
  TAILLE FLOAT,
  POIDS FLOAT,
  TENSION FLOAT,
  TEMP FLOAT,
  FREQ_CARD INT,
  IMC FLOAT,
  RESULTAT VARCHAR(50),
  CONSULTATION_ID INT,
  FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS)
);

-- Table: ORDONNANCE
CREATE TABLE ORDONNANCE (
  NUM_ORDO INT AUTO_INCREMENT PRIMARY KEY,
  DATE_ORDO DATE NOT NULL,
  CONSULTATION_ID INT,
  FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS)
);

-- Table: MEDICAMENT
CREATE TABLE MEDICAMENT (
  NUM_MED INT AUTO_INCREMENT PRIMARY KEY,
  NOM_MED VARCHAR(100),
  DOSAGE VARCHAR(50)
);

-- Table: PRESCRIPTION
CREATE TABLE PRESCRIPTION (
  NBRE_FOIS INT,
  QUANTITE_MED INT,
  FORM_MED VARCHAR(50),
  MEDICAMENT_ID INT,
  ORDONNANCE_ID INT,
  PRIMARY KEY (MEDICAMENT_ID, ORDONNANCE_ID),
  FOREIGN KEY (MEDICAMENT_ID) REFERENCES MEDICAMENT (NUM_MED),
  FOREIGN KEY (ORDONNANCE_ID) REFERENCES ORDONNANCE (NUM_ORDO)
);

-- Table: CERTIFICAT
CREATE TABLE CERTIFICAT (
  NUM_CERT INT AUTO_INCREMENT PRIMARY KEY,
  COMMENTAIRE_CERT VARCHAR(100),
  DATE_NAIS DATE,
  CONSULTATION_ID INT,
  FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS)
);

-- Table: MVT_CAISSE
CREATE TABLE MVT_CAISSE (
  NUM_MVT INT AUTO_INCREMENT PRIMARY KEY,
  TYPE_MVT VARCHAR(50),
  CONSULTATION_ID INT,
  FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS)
);

-- Table: RECETTE
CREATE TABLE RECETTE (
  NUM_REC INT AUTO_INCREMENT PRIMARY KEY,
  DATE_REC DATE,
  TARIF_CONS FLOAT,
  MODE_PAIEMENT VARCHAR(50),
  CONSULTATION_ID INT,
  FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS)
);

-- Table: DEPENSES
CREATE TABLE DEPENSES (
  NUM_DEP INT AUTO_INCREMENT PRIMARY KEY,
  DATE_DEP DATE,
  MOTIF_DEP VARCHAR(50),
  MONTANT_DEP FLOAT,
  CONSULTATION_ID INT,
  FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS)
);

-- Table: IMPAYER
CREATE TABLE IMPAYER (
  NUM_IMP INT AUTO_INCREMENT PRIMARY KEY,
  TELE_PAT VARCHAR(50),
  MONTANT_SUIVIE FLOAT,
  MONTANT_RESTE_SUIVIE FLOAT,
  CONSULTATION_ID INT,
  FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS)
);




INSERT INTO CNAM (DATE_VAL_CNAM, TYPE_CNAM)
VALUES ('2023-05-01', 'Type1'),
       ('2023-05-02', 'Type2'),
       ('2023-05-03', 'Type3'),
       ('2023-05-04', 'Type4'),
       ('2023-05-05', 'Type5');


INSERT INTO RDV (DESCRIPTION, DATE_RDV, HEURE_RDV)
VALUES ('Description1', '2023-05-01', '12:00:00'),
       ('Description2', '2023-05-02', '14:30:00'),
       ('Description3', '2023-05-03', '09:45:00'),
       ('Description4', '2023-05-04', '16:15:00'),
       ('Description5', '2023-05-05', '11:30:00');



INSERT INTO Patient (CIN, DAT_FIC, NOM, PRENOM, DAT_NAI, PROF, ADRESSE, PHONE, SEX, CNAM_ID, RDV_ID)
VALUES (123456789, '2023-05-01', 'Nom1', 'Prénom1', '2000-01-01', 'Profession1', 'Adresse1', 123456789, 'Homme', 1, 6),
       (987654321, '2023-05-02', 'Nom2', 'Prénom2', '1995-05-10', 'Profession2', 'Adresse2', 987654321, 'Femme', ', 2, 7),
       (111222333, '2023-05-03', 'Nom3', 'Prénom3', '1988-12-25', 'Profession3', 'Adresse3', 555555555, 'Homme', ', 3, 8),
       (444555666, '2023-05-04', 'Nom4', 'Prénom4', '1992-07-15', 'Profession4', 'Adresse4', 999999999, 'Femme', 4, 9),
       (777888999, '2023-05-05', 'Nom5', 'Prénom5', '1997-03-20', 'Profession5', 'Adresse5', 888888888, 'Homme', ', 5, 10);


INSERT INTO ANTECEDENT (CATEGORIE, DESCRIPTION, PATIENT_ID)
VALUES ('Catégorie1', 'Description1', 1),
       ('Catégorie2', 'Description2', 2),
       ('Catégorie3', 'Description3', 3),
       ('Catégorie4', 'Description4', 4),
       ('Catégorie5', 'Description5', 5);


INSERT INTO CONSULTATION (DATE_CONS, MOTIF, DIAGNOSTIC, PATIENT_ID)
VALUES ('2023-05-01', 'Motif1', 'Diagnostic1', 1),
       ('2023-05-02', 'Motif2', 'Diagnostic2', 2),
       ('2023-05-03', 'Motif3', 'Diagnostic3', 3),
       ('2023-05-04', 'Motif4', 'Diagnostic4', 4),
       ('2023-05-05', 'Motif5', 'Diagnostic5', 5);


INSERT INTO EXAMEN (DESCRIPTION, TAILLE, POIDS, TENSION, TEMP, FREQ_CARD, IMC, RESULTAT, CONSULTATION_ID)
VALUES ('Description1', 170, 65, 120, 36.5, 80, 22.5, 'Résultat1', 1),
       ('Description2', 165, 70, 130, 37.0, 75, 25.7, 'Résultat2', 2),
       ('Description3', 175, 80, 140, 36.8, 85, 26.1, 'Résultat3', 3),
       ('Description4', 160, 55, 110, 36.2, 70, 21.5, 'Résultat4', 4),
       ('Description5', 180, 75, 125, 36.9, 78, 23.1, 'Résultat5', 5);


INSERT INTO ORDONNANCE (DATE_ORDO, CONSULTATION_ID)
VALUES ('2023-05-01', 1),
       ('2023-05-02', 2),
       ('2023-05-03', 3),
       ('2023-05-04', 4),
       ('2023-05-05', 5);

INSERT INTO MEDICAMENT (NOM_MED, DOSAGE)
VALUES ('Médicament1', 'Dosage1'),
       ('Médicament2', 'Dosage2'),
       ('Médicament3', 'Dosage3'),
       ('Médicament4', 'Dosage4'),
       ('Médicament5', 'Dosage5');


INSERT INTO PRESCRIPTION (NBRE_FOIS, QUANTITE_MED, FORM_MED, MEDICAMENT_ID, ORDONNANCE_ID)
VALUES (3, 10, 'Forme1', 1, 1),
       (2, 5, 'Forme2', 2, 2),
       (1, 2, 'Forme3', 3, 3),
       (4, 8, 'Forme4', 4, 4),
       (2, 6, 'Forme5', 5, 5);


INSERT INTO CERTIFICAT (COMMENTAIRE_CERT, DATE_NAIS, CONSULTATION_ID)
VALUES ('Commentaire1', '2000-01-01', 1),
       ('Commentaire2', '1995-05-10', 2),
       ('Commentaire3', '1988-12-25', 3),
       ('Commentaire4', '1992-07-15', 4),
       ('Commentaire5', '1997-03-20', 5);


INSERT INTO LETTRE (DATE_LETT, NOM_CONF, PRENOM_CONF, SPEC_CONF, COMMENTAIRE, CONSULTATION_ID)
VALUES ('2023-05-01', 'NomConf1', 'PrenomConf1', 'SpecConf1', 'Commentaire1', 1),
       ('2023-05-02', 'NomConf2', 'PrenomConf2', 'SpecConf2', 'Commentaire2', 2),
       ('2023-05-03', 'NomConf3', 'PrenomConf3', 'SpecConf3', 'Commentaire3', 3),
       ('2023-05-04', 'NomConf4', 'PrenomConf4', 'SpecConf4', 'Commentaire4', 4),
       ('2023-05-05', 'NomConf5', 'PrenomConf5', 'SpecConf5', 'Commentaire5', 5);


INSERT INTO MVT_CAISSE (TYPE_MVT, CONSULTATION_ID)
VALUES ('TypeMvt1', 1),
       ('TypeMvt2', 2),
       ('TypeMvt3', 3),
       ('TypeMvt4', 4),
       ('TypeMvt5', 5);

INSERT INTO RECETTE (DATE_REC, TARIF_CONS, MODE_PAIEMENT, CONSULTATION_ID)
VALUES ('2023-05-01', 100.50, 'ModePaiement1', 1),
       ('2023-05-02', 75.25, 'ModePaiement2', 2),
       ('2023-05-03', 120.75, 'ModePaiement3', 3),
       ('2023-05-04', 90.80, 'ModePaiement4', 4),
       ('2023-05-05', 60.40, 'ModePaiement5', 5);


INSERT INTO DEPENSES (DATE_DEP, MOTIF_DEP, MONTANT_DEP, CONSULTATION_ID)
VALUES ('2023-05-01', 'MotifDep1', 50.25, 1),
       ('2023-05-02', 'MotifDep2', 30.50, 2),
       ('2023-05-03', 'MotifDep3', 40.75, 3),
       ('2023-05-04', 'MotifDep4', 20.80, 4),
       ('2023-05-05', 'MotifDep5', 10.60, 5);


INSERT INTO IMPAYER (TELE_PAT, MONTANT_SUIVIE, MONTANT_RESTE_SUIVIE, CONSULTATION_ID)
VALUES ('TéléPat1', 50.25, 25.50, 1),
       ('TéléPat2', 30.50, 15.25, 2),
       ('TéléPat3', 40.75, 20.40, 3),
       ('TéléPat4', 20.80, 10.40, 4),
       ('TéléPat5', 10.60, 5.30, 5);

***********************mettre les clés étrangères en cascades******************************
-- Modifier la clé étrangère dans la table Patient
ALTER TABLE Patient
DROP FOREIGN KEY Patient_ibfk_1,
DROP FOREIGN KEY Patient_ibfk_2,
ADD CONSTRAINT Patient_fk1 FOREIGN KEY (NUM_CNAM) REFERENCES CNAM (NUM_CNAM) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT Patient_fk2 FOREIGN KEY (NUM_RDV) REFERENCES RDV (NUM_RDV) ON DELETE CASCADE ON UPDATE CASCADE;

-- Modifier la clé étrangère dans la table ANTECEDENT
ALTER TABLE ANTECEDENT
DROP FOREIGN KEY ANTECEDENT_ibfk_1,
ADD CONSTRAINT ANTECEDENT_fk1 FOREIGN KEY (PATIENT_ID) REFERENCES Patient (NUM_FIC) ON DELETE CASCADE ON UPDATE CASCADE;

-- Modifier la clé étrangère dans la table CONSULTATION
ALTER TABLE CONSULTATION
DROP FOREIGN KEY CONSULTATION_ibfk_1,
ADD CONSTRAINT CONSULTATION_fk1 FOREIGN KEY (PATIENT_ID) REFERENCES Patient (NUM_FIC) ON DELETE CASCADE ON UPDATE CASCADE;

-- Modifier la clé étrangère dans la table EXAMEN
ALTER TABLE EXAMEN
DROP FOREIGN KEY EXAMEN_ibfk_1,
ADD CONSTRAINT EXAMEN_fk1 FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS) ON DELETE CASCADE ON UPDATE CASCADE;

-- Modifier la clé étrangère dans la table ORDONNANCE
ALTER TABLE ORDONNANCE
DROP FOREIGN KEY ORDONNANCE_ibfk_1,
ADD CONSTRAINT ORDONNANCE_fk1 FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS) ON DELETE CASCADE ON UPDATE CASCADE;

-- Modifier la clé étrangère dans la table CERTIFICAT
ALTER TABLE CERTIFICAT
DROP FOREIGN KEY CERTIFICAT_ibfk_1,
ADD CONSTRAINT CERTIFICAT_fk1 FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS) ON DELETE CASCADE ON UPDATE CASCADE;

-- Modifier la clé étrangère dans la table MVT_CAISSE
ALTER TABLE MVT_CAISSE
DROP FOREIGN KEY MVT_CAISSE_ibfk_1,
ADD CONSTRAINT MVT_CAISSE_fk1 FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS) ON DELETE CASCADE ON UPDATE CASCADE;

-- Modifier la clé étrangère dans la table RECETTE
ALTER TABLE RECETTE
DROP FOREIGN KEY RECETTE_ibfk_1,
ADD CONSTRAINT RECETTE_fk1 FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS) ON DELETE CASCADE ON UPDATE CASCADE;

-- Modifier la clé étrangère dans la table DEPENSES
ALTER TABLE DEPENSES
DROP FOREIGN KEY DEPENSES_ibfk_1,
ADD CONSTRAINT DEPENSES_fk1 FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS) ON DELETE CASCADE ON UPDATE CASCADE;

-- Modifier la clé étrangère dans la table IMPAYER
ALTER TABLE IMPAYER
DROP FOREIGN KEY IMPAYER_ibfk_1,
ADD CONSTRAINT IMPAYER_fk1 FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION (NUM_CONS) ON DELETE CASCADE ON UPDATE CASCADE;

-- Modifier la clé étrangère dans la table PRESCREPTION

-- Supprimer les contraintes de clé étrangère existantes
ALTER TABLE PRESCRIPTION
DROP FOREIGN KEY PRESCRIPTION_ibfk_1,
DROP FOREIGN KEY PRESCRIPTION_ibfk_2;

-- Ajouter les contraintes de clé étrangère avec cascade DELETE et cascade UPDATE
ALTER TABLE PRESCRIPTION
ADD CONSTRAINT PRESCRIPTION_fk1 FOREIGN KEY (MEDICAMENT_ID) REFERENCES MEDICAMENT (NUM_MED) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT PRESCRIPTION_fk2 FOREIGN KEY (ORDONNANCE_ID) REFERENCES ORDONNANCE (NUM_ORDO) ON DELETE CASCADE ON UPDATE CASCADE;

